global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  insecure: false
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
          priority: 10

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: leresolver
  gitlabssh:
    address: ":30022"
  logstashtcp:
    address: ":50000"
  logstashudp:
    address: ":50000/udp"
  elasticsearch:
    address: ":9300"
  logstashbeats:
    address: ":5044"
  


serversTransport:
  insecureSkipVerify: true
  maxIdleConnsPerHost: 42
  forwardingTimeouts:
    dialTimeout: 42
    responseHeaderTimeout: 42
    idleConnTimeout: 42

providers:
  providersThrottleDuration: 42
  docker:
    endpoint: unix:///var/run/docker.sock
    #tls:
      #ca: foobar
      #caOptional: true
      #cert: foobar
      #key: foobar
      #insecureSkipVerify: true
    exposedByDefault: false
    #useBindPortIP: true
    swarmMode: false
    network: traefik
    #swarmModeRefreshSeconds: 42
  file:
    filename: /etc/traefik/dynamic.yml

certificatesResolvers:
  leresolver:
    acme:
      email: ts.infraxs+traefik@gmail.com
      storage: /letsencrypt.json
      # domains: 
      #   main: "*.flouro.mydbsapps.com"
      #   sans: 
      #     - "*.flouro.mydbsapps.com"
      dnschallenge:
        provider: "route53"
        resolvers:
          - 8.8.8.8:53